import fs from'node:fs';import vm from'node:vm';
const H={},on=(n,f)=>(H[n]??=[]).push(f),ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:()=>({width:10})},{get:(o,k)=>k in o?o[k]:(()=>{})}),canvas={getContext:()=>ctx,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:720}),addEventListener:(n,f)=>on('c:'+n,f)},node=()=>({gain:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){},stop(){}});class AudioContext{constructor(){this.currentTime=0;this.destination={}}createGain(){return node()}createOscillator(){return node()}}
const box={console,Math,Date,Uint8Array,AudioContext,localStorage:{},document:{getElementById:()=>canvas,createElement:()=>({width:0,height:0,getContext:()=>ctx})},addEventListener:(n,f)=>on(n,f),requestAnimationFrame:()=>{}};vm.createContext(box);vm.runInContext(['core.js','herd.js','render.js','ui.js','top10.js','polish.js','hud12.js','whip.js','worlds.js','expansion.js'].map(f=>fs.readFileSync('src/'+f,'utf8')).join('\n'),box);const e=s=>vm.runInContext(s,box);
e('startLevel(1);LM.slice(0,-1).forEach(l=>l.os.forEach(o=>o.hp=0))');let hp=e('LM[4].os[0].hp');e('hitObj(unis[0],LM[4].os[0],999)');if(e('LM[4].os[0].hp')!==hp||!e("msg.includes('28% CHAOS')"))throw Error('Town Hall chaos gate');
e('painted=PW*PH*.4;hitObj(unis[0],LM[4].os[0],999)');if(!e('landWin'))throw Error('Town Hall should unlock after landmarks + chaos');
e('timeLeft=75;painted=PW*PH*.08;townDamage=townMax*.16;chains=0;actT=40;actS=40*1.5;stuns=0');let low=e('comp()');if(low>=120000||e('tier(low)')!=='LOW')throw Error('minimal conquest must remain low tier');
e('timeLeft=45;painted=PW*PH*.55;townDamage=townMax*.58;chains=4;actT=60;actS=60*4.5;stuns=6');let high=e('comp()');if(high<=low||!['HIGH','HIGHER','HIGHEST'].includes(e('tier(high)')))throw Error('skillful run must outrank minimal conquest');
e("landWin=1;state='end';startLevel(1)");if(e('zone')!==1||e('timeLeft')!==94||!e('heli'))throw Error('Washwater progression');
e("landWin=1;state='end';startLevel(1)");if(e('zone')!==2||e('timeLeft')!==90)throw Error('Cloudtop progression');
e("S.s('ccC2',1);state='end';landWin=1;startLevel(1)");if(!e('plus')||e('zone')!==0||e('timeLeft')!==94)throw Error('Stampede+ progression');
console.log(`competitive v0.21 smoke: PASS low=${low} skilled=${high}`);
