'use strict';
const C=document.getElementById('game')||document.getElementById('c'),X=C.getContext('2d');
const W=1280,H=720,TAU=Math.PI*2,cl=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const keys={},mouse={x:W*.68,y:H*.5,l:0},S={get:k=>{try{return +localStorage[k]||0}catch{return 0}},set:(k,v)=>{try{localStorage[k]=v}catch{}}};
let state='title',paused=0,last=0,clock=0,rng=Math.random,cam=0,score=0,best=S.get('ccBest'),active=0,swapCd=0,runTime=0,timeLeft=90,flash=0,shake=0,muted=0;
let unis,objs,people,cars,particles,paint,painted,townMax,townDamage,combo=1,comboT=0,team=1,tutorial,musicNext=0,finish=5200,daySeed=1;
const CELL=80,GW=65,GH=9,GOAL=.55,names=['Bolt','Daisy','Bumper','Mallow','Comet','Pickles'],hues=[8,43,116,184,226,292];
const pers=[{sp:1.18,wild:.5,pow:1},{sp:.94,wild:.35,pow:.9},{sp:1,wild:.75,pow:1.35},{sp:.9,wild:.2,pow:1.08},{sp:1.08,wild:1,pow:1.05},{sp:1,wild:1.35,pow:1.18}];
const lines=['NOT THE BAKERY!','That was my bus stop!','Honestly? Iconic.','Who insures magic?','THE FLOWERS!','My commute!','RAINBOW DAMAGE!','Cute pony!','Glitter goat!','Ma’am, this is a crosswalk.','I just painted that!','Do the fountain next!'];
function seeded(s){return()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function today(){let d=new Date;return +`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,0)}${String(d.getDate()).padStart(2,0)}`}
function R(a=1,b=0){return b+rng()*(a-b)}
function reset(){
 daySeed=today();rng=seeded(daySeed);score=0;cam=0;active=0;swapCd=0;runTime=0;timeLeft=90;flash=shake=0;combo=1;comboT=0;team=1;painted=0;townDamage=0;paint=new Uint8Array(GW*GH);unis=[];objs=[];people=[];cars=[];particles=[];
 for(let i=0;i<6;i++)unis.push({x:420+i*820,y:R(500,210),vx:0,vy:0,a:0,h:hues[i],name:names[i],p:pers[i],anger:R(.35,.08),stun:0,charge:0,beam:0,ai:0,tx:0,ty:0,wreck:0,trail:[]});
 buildTown();tutorial={step:0,t:0,done:S.get('ccTut2')};state='play';
}
function buildTown(){townMax=0;for(let i=0;i<27;i++){for(let s of [0,1]){let w=R(165,115),h=R(126,82),x=130+i*190+R(25,-25),y=s?H-h-20:20,max=R(190,120),o={t:'b',x,y,w,h,hp:max,max,val:w*h/900,hue:(i*31+s*90)%360};objs.push(o);townMax+=o.val}}
 for(let i=0;i<18;i++){let t=i%3?'k':'f',w=t==='f'?84:52,h=t==='f'?84:46,x=320+i*280+R(60,-60),y=R(500,210),max=t==='f'?130:70,o={t,x,y,w,h,hp:max,max,val:w*h/1200,hue:(i*47)%360};objs.push(o);townMax+=o.val}
 for(let i=0;i<62;i++)people.push({x:R(finish-120,150),y:R(610,110),vx:0,vy:0,t:R(2),talk:0,line:'',cool:R(4),h:R(360)});
 for(let i=0;i<17;i++)cars.push({x:520+i*300+R(80,-80),y:R(H),vy:R(155,105)*(i%2?1:-1),w:i%5?42:72,h:i%5?82:142,col:i%3});
}
function pick(i){active=(i+6)%6;swapCd=.2;let u=unis[active];cam=cl(u.x-W*.42,0,finish-W);tone(520,.06,'sine',.025,760);fx(u.x,u.y,10,80)}
function paintAt(u,x=u.x,y=u.y,r=0){let cx=Math.floor(x/CELL),cy=Math.floor(y/CELL);for(let yy=-r;yy<=r;yy++)for(let xx=-r;xx<=r;xx++){let a=cx+xx,b=cy+yy;if(a<0||a>=GW||b<0||b>=GH)continue;let k=b*GW+a;if(!paint[k]){paint[k]=1+Math.floor(u.h/45);painted++;score+=Math.round(18*combo*(1+.28*(team-1)));u.wreck=1.2}}}
function damageObj(u,o,d){if(o.hp<=0||d<=0)return;let old=o.hp;o.hp=Math.max(0,o.hp-d);let done=old-o.hp,vol=done/o.max*o.val;townDamage+=vol;u.wreck=1.7;comboT=1.8;combo=Math.min(8,combo+done*.006);team=Math.max(1,unis.filter(q=>q.wreck>0).length);score+=Math.round(vol*260*combo*(1+.32*(team-1)));if(old>0&&o.hp===0){fx(o.x+o.w/2,o.y+o.h/2,24,210);tone(110,.16,'square',.025,55);shake=10}}
function rainbowPct(){return cl(.56*(painted/(GW*GH))+.44*(townDamage/townMax),0,1)}
function nearestObj(u,range=9999){let best=null,bd=range;for(let o of objs)if(o.hp>0){let x=o.x+o.w/2,y=o.y+o.h/2,d=Math.hypot(x-u.x,y-u.y);if(d<bd){bd=d;best=o}}return best}
function beam(u,dt){let wx=mouse.x+cam,wy=mouse.y,dx=wx-u.x,dy=wy-u.y,d=Math.hypot(dx,dy)||1,reach=285;dx/=d;dy/=d;let ex=u.x+dx*Math.min(d,reach),ey=u.y+dy*Math.min(d,reach);u.beam=.07;u.a=Math.atan2(dy,dx);paintAt(u,ex,ey,1);for(let o of objs)if(o.hp>0){let ox=o.x+o.w/2,oy=o.y+o.h/2;if(Math.abs(ox-ex)<o.w/2+58&&Math.abs(oy-ey)<o.h/2+58)damageObj(u,o,dt*74*u.p.pow)}u.anger=cl(u.anger+dt*.035,0,1)}
function charge(u){if(u.charge||u.stun)return;let wx=mouse.x+cam,wy=mouse.y,a=Math.atan2(wy-u.y,wx-u.x);u.a=a;u.vx=Math.cos(a)*720*u.p.sp;u.vy=Math.sin(a)*720*u.p.sp;u.charge=.48;u.anger=cl(u.anger+.16,0,1);fx(u.x,u.y,14,130);tone(130,.14,'sawtooth',.04,480)}
addEventListener('keydown',e=>{keys[e.code]=1;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if((e.code==='Enter'||e.code==='Space')&&state==='title'){audio();reset();return}if(state==='end'&&(e.code==='Enter'||e.code==='Space'))reset();if((e.code==='ShiftLeft'||e.code==='ShiftRight')&&!e.repeat&&state==='play')pick(active+1);if(/^Digit[1-6]$/.test(e.code)&&state==='play')pick(+e.code.slice(-1)-1);if(e.code==='KeyP'||e.code==='Escape')paused=!paused;if(e.code==='KeyM'&&master){muted=!muted;master.gain.value=muted?0:.18}});
addEventListener('keyup',e=>keys[e.code]=0);C.addEventListener('mousemove',e=>{let r=C.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height});C.addEventListener('mousedown',e=>{audio();if(state==='title'||state==='end'){reset();return}if(e.button===0)mouse.l=1});addEventListener('mouseup',e=>{if(e.button===0)mouse.l=0});C.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('blur',()=>{mouse.l=0;for(let k in keys)keys[k]=0});
let AC,master;function audio(){if(AC)return;AC=new (AudioContext||webkitAudioContext)();master=AC.createGain();master.gain.value=.18;master.connect(AC.destination)}function tone(f=220,d=.08,type='sine',v=.03,f2=0){if(!AC)return;let o=AC.createOscillator(),g=AC.createGain(),t=AC.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);if(f2)o.frequency.exponentialRampToValueAtTime(f2,t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start();o.stop(t+d)}
function fx(x,y,n=8,s=100){for(let i=0;i<n;i++){let a=R(TAU),v=R(s,s*.25);particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:R(.8,.25),h:R(360)})}}
function update(dt){if(state!=='play'||paused)return;clock+=dt;runTime+=dt;timeLeft=Math.max(0,90-runTime);swapCd=Math.max(0,swapCd-dt);flash=Math.max(0,flash-dt*3);shake=Math.max(0,shake-dt*22);comboT=Math.max(0,comboT-dt);if(!comboT)combo=lerp(combo,1,dt*2.2);for(let u of unis)u.wreck=Math.max(0,u.wreck-dt);team=Math.max(1,unis.filter(u=>u.wreck>0).length);
 updatePeople(dt);updateCars(dt);updateUnicorns(dt);updateParticles(dt);updateTutorial(dt);let u=unis[active];cam=lerp(cam,cl(u.x-W*.42,0,finish-W),dt*5);
 if(timeLeft<=0){let pct=rainbowPct();score=Math.round(score+(pct>=GOAL?4500:0)+townDamage*25);best=Math.max(best,score);S.set('ccBest',best);state='end';tone(pct>=GOAL?330:140,.55,'triangle',.05,pct>=GOAL?990:90)}}
function updateCars(dt){for(let c of cars){c.y+=c.vy*dt;if(c.vy>0&&c.y>H+120)c.y=-120;if(c.vy<0&&c.y<-120)c.y=H+120;for(let u of unis){if(u.stun)continue;if(Math.abs(u.x-c.x)<c.w/2+15&&Math.abs(u.y-c.y)<c.h/2+14){u.vx+=(u.x-c.x)*5;u.vy=Math.sign(u.y-c.y||1)*380;u.stun=.45;u.anger=cl(u.anger+.22,0,1);flash=.5;shake=7;fx(u.x,u.y,10,130);tone(90,.08,'square',.02,55)}}}}
function updatePeople(dt){for(let p of people){p.t-=dt;p.cool-=dt;p.talk=Math.max(0,p.talk-dt);let close=null,bd=999;for(let u of unis){let d=Math.hypot(u.x-p.x,u.y-p.y);if(d<bd){bd=d;close=u}}if(bd<90){let a=Math.atan2(p.y-close.y,p.x-close.x);p.vx+=Math.cos(a)*dt*420;p.vy+=Math.sin(a)*dt*420;if(p.cool<0){p.line='NOPE!';p.talk=1;p.cool=2}}else if(bd<190&&p.cool<0&&rng()<dt*.75){let insult=rng()<.45;p.line=insult?lines[(rng()*10|0)]:lines[(6+rng()*6|0)];p.talk=1.8;p.cool=R(7,3);if(insult)close.anger=cl(close.anger+R(.2,.09),0,1)}if(p.t<0){p.t=R(2.5,.8);p.vx+=R(45,-45);p.vy+=R(35,-35)}p.x=cl(p.x+p.vx*dt,40,finish-40);p.y=cl(p.y+p.vy*dt,85,H-85);p.vx*=Math.pow(.14,dt);p.vy*=Math.pow(.14,dt)}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.12,dt);p.vy*=Math.pow(.12,dt);if(p.life<=0)particles.splice(i,1)}}
