'use strict';

// Corni Cross - source-first implementation. Competition build is generated by scripts/build.mjs.
const C=document.getElementById('game')||document.getElementById('c'),X=C.getContext('2d');
const W=1280,H=720,TAU=Math.PI*2,cl=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
const keys={},mouse={x:W*.7,y:H*.5,l:0,r:0},S={get:k=>{try{return +localStorage[k]||0}catch{return 0}},set:(k,v)=>{try{localStorage[k]=v}catch{}}};
let state='title',paused=0,last=0,clock=0,seed=1,rng=Math.random,cam=0,score=0,best=S.get('ccBest'),level=0;
let player,unis,cars,props,particles,pigeons,finish,meter,burst,dashCd,runTime,damage,near,chainMax,chainNow,tutorial,flash,shake,daySeed,musicNext,readyPing,muted;
const names=['Bolt','Daisy','Bumper','Mallow','Comet','Pickles','Nova','Fizz'];
const hues=[8,42,118,184,222,286,324,58];
const personalities=[
  {speed:1.14,coh:.82,wander:.55,food:.15},
  {speed:.94,coh:1.02,wander:.35,food:1.6},
  {speed:1.03,coh:.72,wander:.65,food:.25},
  {speed:.91,coh:1.35,wander:.18,food:.6},
  {speed:1.08,coh:.9,wander:.9,food:.2},
  {speed:.98,coh:.78,wander:1.35,food:.85},
  {speed:1.0,coh:1.08,wander:.42,food:.3},
  {speed:1.07,coh:.94,wander:.7,food:.45}
];

function seeded(s){return()=>{s|=0;s=s+0x6D2B79F5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function today(){let d=new Date;return +`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,0)}${String(d.getDate()).padStart(2,0)}`}
function R(a=1,b=0){return b+rng()*(a-b)}
function reset(){
  level=0;seed=daySeed=today();rng=seeded(seed);cam=0;score=0;meter=.28;burst=0;dashCd=0;runTime=0;damage=0;near=0;chainMax=chainNow=1;flash=shake=0;musicNext=readyPing=0;
  player={x:230,y:360,vx:0,vy:0,a:0}; unis=[]; cars=[]; props=[]; particles=[]; pigeons=[];
  for(let i=0;i<6;i++)unis.push({x:140+R(120),y:275+R(170),vx:R(30,-10),vy:R(20,-20),a:0,h:hues[i],p:personalities[i],name:names[i],daze:0,wander:R(9),trail:[],near:0,home:0});
  finish=6060;tutorial={step:0,t:0,done:S.get('ccTut')};
  buildTown(); state='play';
}
function buildTown(){
  const xs=[900,1680,2500,3380,4300,5150].map(x=>x+R(60,-60));
  xs.forEach((x,i)=>{
    props.push({t:'cross',x,w:150});
    let count=i>3?4:3;
    for(let j=0;j<count;j++)cars.push(makeCar(x+R(80,-80),-180-j*250-R(220),i,j));
  });
  props.push({t:'fountain',x:1370+R(80,-80),y:R(250,195),r:62},{t:'cart',x:2140+R(80,-80),y:R(535,485),r:32},{t:'cones',x:3000+R(70,-70),y:R(270,220),w:260,h:70},{t:'fountain',x:3900+R(80,-80),y:R(530,480),r:54},{t:'cart',x:4820+R(80,-80),y:R(235,185),r:32},{t:'cones',x:5450+R(70,-70),y:R(480,430),w:250,h:66});
  for(let i=0;i<15;i++)pigeons.push({x:R(5650,550),y:R(580,130),vx:0,vy:0,f:0,a:R(TAU)});
}
function makeCar(x,y,i,j){let bus=(i===3&&j===0)||(i===5&&j===1);return{x,y,w:bus?76:42,h:bus?150:82,vy:(105+i*12)*(j%2?1:1),base:y,phase:R(6),bus,col:(i+j)%3};}

addEventListener('keydown',e=>{keys[e.code]=1;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if((e.code==='Enter'||e.code==='Space')&&state==='title'){audio();reset()}if(e.code==='KeyP'||e.code==='Escape')paused=!paused;if(e.code==='KeyM'&&master){muted=!muted;master.gain.value=muted?0:.18}if(e.code==='KeyR'&&state==='play'&&meter>=1){meter=0;burst=2.7;fx(player.x,player.y,40,170);tone(180,.22,'sawtooth',.08,360)}});
addEventListener('keyup',e=>keys[e.code]=0);
C.addEventListener('mousemove',e=>{let r=C.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height});
C.addEventListener('mousedown',e=>{audio();if(state==='title'){reset();return}if(state==='end'){reset();return}if(e.button===0)mouse.l=1;if(e.button===2)mouse.r=1});
addEventListener('mouseup',e=>{if(e.button===0)mouse.l=0;if(e.button===2)mouse.r=0});
C.addEventListener('contextmenu',e=>e.preventDefault());

let AC,master;
function audio(){if(AC)return;AC=new (AudioContext||webkitAudioContext)();master=AC.createGain();master.gain.value=.18;master.connect(AC.destination)}
function tone(f=.1,d=.08,type='sine',v=.03,f2=0){if(!AC)return;let o=AC.createOscillator(),g=AC.createGain(),t=AC.currentTime;o.type=type;o.frequency.setValueAtTime(f,t);if(f2)o.frequency.exponentialRampToValueAtTime(f2,t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(master);o.start(t);o.stop(t+d)}
function ping(kind){if(kind===0)tone(950,.08,'sine',.035,650);if(kind===1)tone(120,.12,'square',.025,70);if(kind===2){tone(250,.18,'triangle',.05,700);tone(500,.13,'sine',.03,900)}}

function update(dt){
  if(state!=='play'||paused)return;clock+=dt;runTime+=dt;flash=Math.max(0,flash-dt*2);shake=Math.max(0,shake-dt*20);burst=Math.max(0,burst-dt);dashCd=Math.max(0,dashCd-dt);
  let mx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0),my=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0),m=Math.hypot(mx,my)||1;
  let speed=265*(burst?1.16:1);player.vx=lerp(player.vx,mx/m*speed,dt*10);player.vy=lerp(player.vy,my/m*speed,dt*10);if(!mx)player.vx*=Math.pow(.02,dt);if(!my)player.vy*=Math.pow(.02,dt);
  let wx=mouse.x+cam,wy=mouse.y;player.a=Math.atan2(wy-player.y,wx-player.x);
  if(keys.Space&&!dashCd){dashCd=1.05;let dx=Math.cos(player.a),dy=Math.sin(player.a);player.vx+=dx*540;player.vy+=dy*540;fx(player.x,player.y,12,100);tone(130,.14,'sawtooth',.035,420);for(let u of unis){let d=Math.hypot(u.x-player.x,u.y-player.y);if(d<155){u.vx+=dx*240;u.vy+=dy*240}}}
  player.x=cl(player.x+player.vx*dt,60,finish+300);player.y=cl(player.y+player.vy*dt,70,H-70);
  updateCars(dt);updatePigeons(dt);updateUnicorns(dt);updateParticles(dt);updateTutorial(dt);
  let herdX=unis.reduce((a,u)=>a+u.x,0)/unis.length;cam=lerp(cam,cl(Math.max(player.x,herdX)-W*.38,0,finish-W*.7),dt*3.4);
  if(unis.every(u=>u.x>finish)){score=Math.max(0,Math.round(6000+meter*1800+chainMax*500+Math.max(0,220-runTime)*18-damage*180+near*90));best=Math.max(best,score);S.set('ccBest',best);state='end';tone(330,.55,'triangle',.05,880);setTimeout(()=>tone(660,.55,'triangle',.04,1100),120)}
}
function updateCars(dt){
  for(let c of cars){c.y+=c.vy*dt*(burst&&Math.abs(c.x-player.x)<430?.24:1); if(c.y>H+220)c.y=-220-R(360); c.x+=Math.sin(clock*.5+c.phase)*dt*4;
    for(let u of unis){if(u.daze>.1)continue;let dx=Math.abs(u.x-c.x),dy=Math.abs(u.y-c.y);if(dx<c.w*.5+16&&dy<c.h*.5+13){let s=Math.sign(u.y-c.y)||1;u.vx+=(u.x-c.x)*5+R(250,80);u.vy=s*430;u.daze=.7;damage++;shake=12;flash=.65;fx(u.x,u.y,18,180);ping(1)}}
    let dx=player.x-c.x,dy=player.y-c.y;if(Math.abs(dx)<c.w*.5+14&&Math.abs(dy)<c.h*.5+14){player.x-=player.vx*dt*2;player.y-=player.vy*dt*2;player.vx*=-.35;player.vy*=-.35}
  }
}
function updatePigeons(dt){for(let p of pigeons){p.f=Math.max(0,p.f-dt);let closest=999;for(let u of unis)closest=Math.min(closest,Math.hypot(u.x-p.x,u.y-p.y));if(closest<75&&!p.f){p.f=3;p.a=R(TAU);p.vx=Math.cos(p.a)*R(130,80);p.vy=Math.sin(p.a)*R(130,80);tone(1200,.025,'square',.008,800)}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.38,dt);p.vy*=Math.pow(.38,dt)}}
