let plus=!!S.g('ccC2'),heat=S.g('ccHeat'),actS=0,actT=0,stuns=0,finalScore=0;
const gates=()=>[6,7,8,9].filter(i=>dmask>>i&1).length,chaos=()=>.28+(plus?Math.min(heat,8)*.01:0);
function comp(){let a=actT?actS/actT/6:0,m=[1,1.12,1.25][zone]*(plus?1.12+Math.min(heat,9)*.04:1);return Math.round(((landWin?2e4:0)+Math.max(0,timeLeft)*600+paintPct()*9e4+structPct()*7e4+Math.min(chains,6)*6e3+a*45e3+Math.min(stuns,10)*1800+gates()*3e3)*m)}
const _plusStart=startLevel;startLevel=function(n){_plusStart(n);plus=!!S.g('ccC2');heat=S.g('ccHeat');actS=actT=stuns=finalScore=0;if(n&&plus){let h=Math.min(heat,9);timeLeft-=4+h;addClean(1+(h>3));for(let c of cars)c.v*=1.08+h*.02;lmText='HEAT '+(h+1)+' • '+ZN[zone];lmTextT=2}};
const _plusClean=updateCleaners;updateCleaners=function(dt){let a=cleaners.map(c=>c.stun);_plusClean(dt);for(let i=cleaners.length;i--;)if(!a[i]&&cleaners[i].stun)stuns++};
const _plusHit=hitObj;hitObj=function(u,o,d){if(o&&o.lm==='hall'&&outerDone()&&takeover()<chaos()){msg='HALL SHIELD • NEED '+(chaos()*100|0)+'% CHAOS';msgT=1;return}_plusHit(u,o,d)};
const _plusZone=updateZone;updateZone=function(dt){_plusZone(dt);if(!level||!plus)return;if(zone!==2)for(let u of unis)if(u.live)u.vx+=Math.sin(clock*.7)*(45+heat*6)*dt;for(let i=4;i--;)if(!(dmask>>i+6&1)){let x=550+i*700,y=i%2?540:1130;for(let u of unis)if(u.live&&Math.hypot(u.x-x,u.y-y)<70){dmask|=64<<i;u.boost+=2;award('PRISM GATE',350);break}}};
const _plusUpdate=update;update=function(dt){let b=state;_plusUpdate(dt);if(b==='play'&&level){actS+=stamp*dt;actT+=dt}if(b==='play'&&state==='end'&&landWin){score=finalScore=comp();best=Math.max(best,score);S.s('ccBest8',best);if(plus)S.s('ccHeat',++heat)}};
const _plusWorld=world;world=function(){_plusWorld();if(!level||!plus)return;X.save();X.translate(ox,oy);X.scale(z,z);for(let i=4;i--;)if(!(dmask>>i+6&1)){let x=550+i*700,y=i%2?540:1130;for(let q=3;q--;){X.strokeStyle=`hsl(${clock*60+i*70+q*100} 100% 65%)`;X.lineWidth=4+q*3;X.beginPath();X.arc(x,y,30+q*11,Math.PI,T);X.stroke()}}X.restore()};
