function distractForce(u){let ax=0,ay=0,best=999,hit=0;for(let o of objs)if(o.t==='fountain'){let x=o.x+o.w/2,y=o.y+o.h/2,dx=x-u.x,dy=y-u.y,d=Math.hypot(dx,dy)||1;if(d<210){let q=(210-d)/210;ax+=dx/d*380*q;ay+=dy/d*380*q;if(d<92){u.distract=Math.max(u.distract,.65);hit=1}}}for(let f of flowers){let dx=f.x-u.x,dy=f.y-u.y,d=Math.hypot(dx,dy)||1;if(d<f.r+115){let q=1-d/(f.r+115);ax+=dx/d*310*q;ay+=dy/d*310*q;if(d<f.r+30){u.distract=Math.max(u.distract,.9);hit=1}}}for(let b of flies){let dx=b.x-u.x,dy=b.y-u.y,d=Math.hypot(dx,dy)||1;if(d<150&&d<best){best=d;ax+=dx/d*250;ay+=dy/d*250;if(d<60){u.distract=Math.max(u.distract,.45);hit=1}}}if(hit)intro.distract=1;return[ax,ay]}
function moveAI(u,dt){u.ai-=dt;if(u.ai<=0){u.ai=R(1.7,.5)/(1+u.anger+u.frenzy);let t=u.frenzy||u.anger>.57?nearestObj(u,u.frenzy?1200:760):null;if(t){u.tx=t.x+t.w/2;u.ty=t.y+t.h/2}else{let p=ups.find(q=>q.on&&Math.hypot(q.x-u.x,q.y-u.y)<520);if(p&&rng()<.55){u.tx=p.x;u.ty=p.y}else{u.tx=cl(u.x+R(780,-780),55,WW-55);u.ty=cl(u.y+R(620,-620),55,WH-55)}}}let dx=u.tx-u.x,dy=u.ty-u.y,d=Math.hypot(dx,dy)||1,s=430*(.38+u.anger*.55+(u.frenzy?1.15:0))*u.p.sp;return[dx/d*s+Math.sin(clock*1.9+u.h)*95*u.p.w,dy/d*s+Math.cos(clock*1.6+u.h)*95*u.p.w]}
function collide(u,o,dt){if(o.hp<=0)return;let ex=20,inside=u.x>o.x-ex&&u.x<o.x+o.w+ex&&u.y>o.y-ex&&u.y<o.y+o.h+ex;if(!inside)return;let sp=Math.hypot(u.vx,u.vy),can=o.t==='b'&&(u.frenzy||u.anger>.72&&sp>125);if(can){hitObj(u,o,dt*(u.frenzy?420:145)*u.p.p);if(rng()<dt*9)fx(u.x,u.y,2,80)}else{let cx=o.x+o.w/2,cy=o.y+o.h/2,a=Math.atan2(u.y-cy,u.x-cx);u.vx+=Math.cos(a)*170;u.vy+=Math.sin(a)*170;if(o.t==='fountain')u.distract=Math.max(u.distract,1.1)}}
function autoSpray(u,dt){u.paint-=dt;u.spray-=dt;let sp=Math.hypot(u.vx,u.vy);if(u.distract>.05)return;if(sp>32&&u.paint<=0){u.paint=u.frenzy?.045:u.boost?.065:.1;paintStamp(u,u.x,u.y,u.frenzy?45:u.boost?36:26)}if((u.frenzy||u.anger>.82)&&u.spray<=0){u.spray=u.frenzy?R(.18,.08):R(.45,.24);let a=R(T),r=R(u.frenzy?170:115,40),x=cl(u.x+Math.cos(a)*r,0,WW),y=cl(u.y+Math.sin(a)*r,0,WH);paintStamp(u,x,y,u.frenzy?R(68,38):R(48,28));let o=nearestObj(u,240);if(o)hitObj(u,o,(u.frenzy?42:18)*u.p.p);fx(x,y,2,55)}}
function updateWorld(dt){for(let b of flies){b.a+=dt*b.s;b.x=cl(b.x+Math.cos(b.a)*dt*36,25,WW-25);b.y=cl(b.y+Math.sin(b.a*.83)*dt*30,25,WH-25)}for(let p of ups){if(!p.on){p.cool-=dt;if(p.cool<=0)p.on=1}}for(let i=0;i<unis.length;i++){let u=unis[i],ctrl=i===active,ax=0,ay=0;u.anger=cl(u.anger-dt*(u.frenzy?0:.018),0,1);if(!u.stun){if(ctrl){let mx=(K.KeyD||K.ArrowRight?1:0)-(K.KeyA||K.ArrowLeft?1:0),my=(K.KeyS||K.ArrowDown?1:0)-(K.KeyW||K.ArrowUp?1:0),m=Math.hypot(mx,my)||1;if(mx||my){intro.moved=1;ax=mx/m*980*u.p.sp;ay=my/m*980*u.p.sp}}else [ax,ay]=moveAI(u,dt);let f=distractForce(u),pull=ctrl?.38:.8;ax+=f[0]*pull;ay+=f[1]*pull;if(u.distract) {ax*=.35;ay*=.35}}
  if(!u.stun){u.vx+=ax*dt;u.vy+=ay*dt}let vmax=(ctrl?350:235+u.anger*145)*(u.frenzy?1.75:u.boost?1.4:1)*u.p.sp,v=Math.hypot(u.vx,u.vy);if(v>vmax){u.vx=u.vx/v*vmax;u.vy=u.vy/v*vmax}u.vx*=Math.pow(u.distract?.08:ctrl?.07:.24,dt);u.vy*=Math.pow(u.distract?.08:ctrl?.07:.24,dt);u.x=cl(u.x+u.vx*dt,20,WW-20);u.y=cl(u.y+u.vy*dt,20,WH-20);if(Math.hypot(u.vx,u.vy)>20)u.a=Math.atan2(u.vy,u.vx);for(let o of objs)collide(u,o,dt);for(let p of ups)if(p.on&&Math.hypot(p.x-u.x,p.y-u.y)<p.r+25)power(u,p);autoSpray(u,dt);u.trail.push([u.x,u.y]);if(u.trail.length>12)u.trail.shift()}
 updateCars(dt);updatePeople(dt);updateParts(dt);updateIntro(dt);if(AC&&clock%1<dt){tone(72+unis.filter(u=>u.frenzy).length*18,.05,'triangle',.006);if(unis.some(u=>u.frenzy))tone(330,.035,'sine',.004)}}
function updateCars(dt){for(let c of cars){if(c.dir){c.x+=c.v*dt;if(c.v>0&&c.x>WW+120)c.x=-120;if(c.v<0&&c.x<-120)c.x=WW+120}else{c.y+=c.v*dt;if(c.v>0&&c.y>WH+120)c.y=-120;if(c.v<0&&c.y<-120)c.y=WH+120}for(let u of unis)if(!u.stun&&Math.abs(u.x-c.x)<c.w/2+18&&Math.abs(u.y-c.y)<c.h/2+18){u.vx+=(u.x-c.x)*4;u.vy+=(u.y-c.y)*4;u.stun=.38;u.anger=cl(u.anger+.2,0,1);paintStamp(u,u.x,u.y,42);flash=.45;shake=5;tone(92,.07,'square',.018,55)}}}
function updatePeople(dt){for(let p of people){p.t-=dt;p.cool-=dt;p.say=Math.max(0,p.say-dt);let u,bd=999;for(let q of unis){let d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){bd=d;u=q}}if(bd<80){let a=Math.atan2(p.y-u.y,p.x-u.x);p.vx+=Math.cos(a)*dt*520;p.vy+=Math.sin(a)*dt*520;if(p.cool<0){p.line='AAAA RAINBOW!';p.say=1;p.cool=2}}else if(bd<170&&p.cool<0&&rng()<dt*.42){p.line=talk[rng()*talk.length|0];p.say=1.7;p.cool=R(8,4);if(rng()<.5)u.anger=cl(u.anger+R(.18,.08),0,1)}if(p.t<0){p.t=R(3,.9);p.vx+=R(45,-45);p.vy+=R(35,-35)}p.x=cl(p.x+p.vx*dt,18,WW-18);p.y=cl(p.y+p.vy*dt,18,WH-18);p.vx*=Math.pow(.12,dt);p.vy*=Math.pow(.12,dt)}}
function updateParts(dt){for(let i=parts.length-1;i>=0;i--){let p=parts[i];p.l-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.pow(.1,dt);p.vy*=Math.pow(.1,dt);if(p.l<=0)parts.splice(i,1)}}
function updateIntro(dt){if(level)return;let s=intro.step;if(s===0&&intro.moved)intro.step=1;if(s===1&&intro.swapped)intro.step=2;if(s===2&&intro.power)intro.step=3;if(s===3&&intro.distract)intro.step=4}