function rr(x,y,w,h,r){X.beginPath();X.roundRect(x,y,w,h,r);X.fill()}
function text(t,x,y,s=20,a='left',alpha=1){X.globalAlpha=alpha;X.font=`800 ${s}px system-ui`;X.textAlign=a;X.fillText(t,x,y);X.globalAlpha=1}
function draw(){let sx=shake?R(shake,-shake):0,sy=shake?R(shake,-shake):0;X.setTransform(1,0,0,1,sx,sy);X.clearRect(-20,-20,W+40,H+40);if(state==='title'){drawTitle();return}drawWorld();drawHUD();if(paused)drawPause();if(state==='end')drawEnd();if(flash){X.fillStyle=`rgba(255,255,255,${flash*.22})`;X.fillRect(0,0,W,H)}}
function drawWorld(){X.fillStyle='#0b1020';X.fillRect(0,0,W,H);X.fillStyle='#20283a';X.fillRect(0,90,W,540);X.fillStyle='#343c4f';X.fillRect(0,160,W,400);X.strokeStyle='#737c90';X.lineWidth=2;X.setLineDash([26,30]);X.beginPath();X.moveTo(0,360);X.lineTo(W,360);X.stroke();X.setLineDash([]);drawPaint();drawObjs();drawCars();drawPeople();for(let u of unis)drawTrail(u);for(let i=0;i<unis.length;i++)drawUni(unis[i],i===active);drawParticles();let a=unis[active];if(a.beam)drawBeam(a)}
function drawPaint(){for(let gy=0;gy<GH;gy++)for(let gx=Math.floor(cam/CELL)-1;gx<Math.floor((cam+W)/CELL)+2;gx++){if(gx<0||gx>=GW)continue;let v=paint[gy*GW+gx];if(!v)continue;let x=gx*CELL-cam,y=gy*CELL;X.fillStyle=`hsla(${(v-1)*45} 90% 58% / .16)`;X.fillRect(x,y,CELL+1,CELL+1);X.strokeStyle=`hsla(${(v-1)*45+30} 95% 70% / .22)`;X.beginPath();X.moveTo(x+8,y+CELL-10);X.quadraticCurveTo(x+CELL*.5,y+10,x+CELL-7,y+CELL*.45);X.stroke()}}
function drawObjs(){for(let o of objs){let x=o.x-cam;if(x>W+140||x+o.w<-140)continue;let d=1-o.hp/o.max,h=o.hue;X.fillStyle=o.t==='b'?'#171d2a':o.t==='f'?'#476170':'#7f6a52';rr(x,o.y,o.w,o.h,o.t==='b'?7:12);if(d){X.fillStyle=`hsla(${h} 90% 60% / ${.22+d*.62})`;rr(x,o.y+o.h*(1-d),o.w,o.h*d,o.t==='b'?6:10);X.strokeStyle=`hsl(${h+70} 90% 72%)`;X.lineWidth=2;for(let k=0;k<3;k++){let xx=x+o.w*(.2+k*.3);X.beginPath();X.moveTo(xx,o.y+o.h*.2);X.lineTo(xx+Math.sin(k+h)*12,o.y+o.h*.55);X.lineTo(xx-5,o.y+o.h*.82);X.stroke()}}if(o.t==='b'){X.fillStyle='#d8c578';for(let wx=14;wx<o.w-8;wx+=34)for(let wy=14;wy<o.h-15;wy+=32)X.fillRect(x+wx,o.y+wy,15,12)}if(o.hp<=0){X.fillStyle=`hsl(${h} 85% 60%)`;for(let k=0;k<5;k++)X.fillRect(x+k*o.w/5,o.y+o.h-10-(k%2)*8,o.w/6,10+(k%2)*8)}}}
function drawCars(){for(let c of cars){let x=c.x-cam;if(x<-90||x>W+90)continue;X.fillStyle=['#ef5b63','#57b8ff','#e7c954'][c.col];rr(x-c.w/2,c.y-c.h/2,c.w,c.h,8);X.fillStyle='#172033';X.fillRect(x-c.w*.32,c.y-c.h*.28,c.w*.64,c.h*.22)}}
function drawPeople(){for(let p of people){let x=p.x-cam;if(x<-30||x>W+30)continue;X.fillStyle=`hsl(${p.h} 35% 70%)`;X.beginPath();X.arc(x,p.y,6,0,TAU);X.fill();X.strokeStyle='#ccd1df';X.lineWidth=2;X.beginPath();X.moveTo(x,p.y+6);X.lineTo(x,p.y+20);X.moveTo(x,p.y+11);X.lineTo(x-7,p.y+16);X.moveTo(x,p.y+11);X.lineTo(x+7,p.y+16);X.stroke();if(p.talk){X.fillStyle='rgba(7,10,18,.88)';let w=Math.min(190,18+p.line.length*7);rr(x-w/2,p.y-43,w,25,9);X.fillStyle='#fff';text(p.line,x,p.y-26,10,'center')}}}
function drawTrail(u){if(u.trail.length<2)return;X.lineCap='round';for(let j=1;j<u.trail.length;j++){let a=u.trail[j-1],b=u.trail[j],q=j/u.trail.length;X.strokeStyle=`hsla(${u.h+j*8} 95% 65% / ${q*.48})`;X.lineWidth=(u.charge?16:7)*q;X.beginPath();X.moveTo(a[0]-cam,a[1]);X.lineTo(b[0]-cam,b[1]);X.stroke()}}
function drawUni(u,on){let x=u.x-cam,y=u.y,b=Math.sin(clock*12+u.h)*2,flip=Math.cos(u.a)<0?-1:1;X.save();X.translate(x,y+b);X.rotate(u.a*.12);X.scale(flip,1);if(on){X.strokeStyle='#fff';X.lineWidth=3;X.globalAlpha=.65;X.beginPath();X.arc(0,0,34+Math.sin(clock*7)*3,0,TAU);X.stroke();X.globalAlpha=1}if(u.anger>.68){X.fillStyle=`hsla(${u.h} 95% 62% / .18)`;X.beginPath();X.arc(0,0,34+u.anger*12,0,TAU);X.fill()}X.fillStyle='rgba(0,0,0,.24)';X.beginPath();X.ellipse(0,15,23,7,0,0,TAU);X.fill();X.strokeStyle=`hsl(${u.h} 95% 62%)`;X.lineWidth=6;X.beginPath();X.moveTo(-20,0);X.quadraticCurveTo(-36,-12,-39,7);X.stroke();X.strokeStyle='#eef0ff';X.lineWidth=5;for(let k of [-11,10]){let kick=Math.sin(clock*18+u.h+k)*8;X.beginPath();X.moveTo(k,9);X.lineTo(k+kick,25);X.stroke()}X.fillStyle=u.stun?'#bfc4d8':'#f7f7ff';X.beginPath();X.ellipse(0,0,23,14,0,0,TAU);X.fill();X.beginPath();X.arc(19,-9,11,0,TAU);X.fill();X.fillStyle=`hsl(${u.h+40} 95% 66%)`;X.beginPath();X.moveTo(23,-18);X.lineTo(38,-38);X.lineTo(30,-14);X.fill();X.fillStyle='#20243a';X.beginPath();X.arc(23,-10,2.5,0,TAU);X.fill();X.restore();if(on){X.fillStyle='#fff';text(`${u.name} ${u.anger>.7?'RAGING':''}`,x,y-42,11,'center')}}
function drawBeam(u){let wx=mouse.x,wy=mouse.y,x=u.x-cam,y=u.y,dx=wx-x,dy=wy-y,d=Math.hypot(dx,dy)||1,r=Math.min(285,d);X.lineCap='round';for(let k=0;k<3;k++){X.strokeStyle=`hsla(${u.h+k*65} 95% 68% / ${.7-k*.18})`;X.lineWidth=11-k*3;X.beginPath();X.moveTo(x,y);X.lineTo(x+dx/d*r,y+dy/d*r);X.stroke()}X.beginPath();X.arc(x+dx/d*r,y+dy/d*r,22+Math.sin(clock*12)*4,0,TAU);X.stroke()}
function drawParticles(){for(let p of particles){X.globalAlpha=cl(p.life*2,0,1);X.fillStyle=`hsl(${p.h} 95% 65%)`;X.fillRect(p.x-cam,p.y,3+p.life*4,3+p.life*4)}X.globalAlpha=1}
