function rr(x,y,w,h,r){X.beginPath();X.roundRect(x,y,w,h,r);X.fill()}function text(t,x,y,s=20,a='left',al=1){X.globalAlpha=al;X.font=`800 ${s}px system-ui`;X.textAlign=a;X.fillText(t,x,y);X.globalAlpha=1}
function draw(){let sx=shake?R(shake,-shake):0,sy=shake?R(shake,-shake):0;X.setTransform(1,0,0,1,sx,sy);X.clearRect(-20,-20,W+40,H+40);if(state==='title'){title();return}if(state==='between'){between();return}world();hud();if(paused)pause();if(state==='end')end();if(flash){X.fillStyle=`rgba(255,255,255,${flash*.2})`;X.fillRect(0,0,W,H)}}
function world(){X.fillStyle='#0c1422';X.fillRect(0,0,W,H);X.save();X.translate(ox,oy);X.scale(z,z);X.fillStyle='#73966a';X.fillRect(0,0,WW,WH);for(let r of roads){X.fillStyle='#3e4651';X.fillRect(...r);X.strokeStyle='#c8b76d';X.lineWidth=3;X.setLineDash([28,28]);X.beginPath();if(r[2]>r[3]){X.moveTo(r[0],r[1]+r[3]/2);X.lineTo(r[0]+r[2],r[1]+r[3]/2)}else{X.moveTo(r[0]+r[2]/2,r[1]);X.lineTo(r[0]+r[2]/2,r[1]+r[3])}X.stroke();X.setLineDash([])}X.globalAlpha=.72;X.drawImage(PC,0,0,PW,PH,0,0,WW,WH);X.globalAlpha=1;drawFlowers();drawObjs();drawUps();drawCars();drawPeople();drawFlies();for(let u of unis)trail(u);for(let i=0;i<unis.length;i++)uni(unis[i],i===active);drawParts();X.restore()}
function drawObjs(){for(let o of objs){if(o.hp<=0&&o.t==='b'){X.fillStyle=`hsl(${o.hue} 70% 48%)`;for(let i=0;i<5;i++)X.fillRect(o.x+i*o.w/5,o.y+o.h-18-(i%2)*10,o.w/6,18+(i%2)*10);continue}if(o.t==='hedge'){X.fillStyle='#315b3b';rr(o.x,o.y,o.w,o.h,18);X.fillStyle='#527e50';for(let x=o.x+15;x<o.x+o.w;x+=34){X.beginPath();X.arc(x,o.y+o.h/2,16,0,T);X.fill()}continue}if(o.t==='fountain'){X.fillStyle='#d3c9b7';X.beginPath();X.arc(o.x+o.w/2,o.y+o.h/2,o.w/2,0,T);X.fill();X.fillStyle='#64bddd';X.beginPath();X.arc(o.x+o.w/2,o.y+o.h/2,o.w*.36,0,T);X.fill();X.strokeStyle='#bff0ff';X.lineWidth=5;X.beginPath();X.arc(o.x+o.w/2,o.y+o.h/2,o.w*.18,0,T);X.stroke();continue}let d=1-o.hp/o.max;X.fillStyle=`hsl(${o.hue} 25% ${35+d*18}%)`;rr(o.x,o.y,o.w,o.h,12);X.fillStyle=`hsl(${o.hue+20} 45% ${52+d*18}%)`;X.beginPath();X.moveTo(o.x-10,o.y+12);X.lineTo(o.x+o.w/2,o.y-32);X.lineTo(o.x+o.w+10,o.y+12);X.closePath();X.fill();X.fillStyle=d?`hsla(${o.hue+120} 90% 60%/${.25+d*.7})`:'#f5d67a';for(let x=o.x+22;x<o.x+o.w-18;x+=44)for(let y=o.y+28;y<o.y+o.h-20;y+=42)X.fillRect(x,y,20,18);if(d>.2){X.strokeStyle='#ffe46e';X.lineWidth=5;X.beginPath();X.moveTo(o.x+o.w*.3,o.y+15);X.lineTo(o.x+o.w*.45,o.y+o.h*.5);X.lineTo(o.x+o.w*.36,o.y+o.h-8);X.stroke()}}}
function drawFlowers(){for(let f of flowers){X.fillStyle='#3f7647';X.beginPath();X.arc(f.x,f.y,f.r,0,T);X.fill();for(let i=0;i<10;i++){let a=i*T/10,r=f.r*.65;X.fillStyle=`hsl(${i*47} 75% 72%)`;X.beginPath();X.arc(f.x+Math.cos(a)*r,f.y+Math.sin(a)*r,10,0,T);X.fill()}}}
function drawFlies(){for(let b of flies){X.fillStyle='#f5d85e';X.beginPath();X.ellipse(b.x-5,b.y,7,4,-.5,0,T);X.ellipse(b.x+5,b.y,7,4,.5,0,T);X.fill()}}
function drawUps(){for(let p of ups)if(p.on){let q=1+Math.sin(clock*6)*.12;X.save();X.translate(p.x,p.y);X.scale(q,q);X.fillStyle=p.t==='rage'?'#ff5f68':p.t==='bomb'?'#ffe45e':'#6be4ff';X.beginPath();X.arc(0,0,p.r,0,T);X.fill();X.strokeStyle='#fff';X.lineWidth=5;X.beginPath();for(let i=0;i<8;i++){let a=i*T/8,r=i%2?13:24;let x=Math.cos(a)*r,y=Math.sin(a)*r;i?X.lineTo(x,y):X.moveTo(x,y)}X.closePath();X.stroke();X.restore();X.fillStyle='#fff';text(p.t==='rage'?'RAGE CORN':p.t==='bomb'?'PRISM POP':'RAINBOW SODA',p.x,p.y-42,18/z,'center')}}
function drawCars(){for(let c of cars){X.fillStyle=['#e95d63','#5aaee8','#e6c85b'][c.col];rr(c.x-c.w/2,c.y-c.h/2,c.w,c.h,10);X.fillStyle='#172233';if(c.dir)X.fillRect(c.x-c.w*.12,c.y-c.h*.32,c.w*.24,c.h*.64);else X.fillRect(c.x-c.w*.32,c.y-c.h*.12,c.w*.64,c.h*.24)}}
function drawPeople(){for(let p of people){X.fillStyle=`hsl(${p.h} 45% 70%)`;X.beginPath();X.arc(p.x,p.y,10,0,T);X.fill();X.strokeStyle='#263242';X.lineWidth=4;X.beginPath();X.moveTo(p.x,p.y+10);X.lineTo(p.x,p.y+30);X.moveTo(p.x,p.y+17);X.lineTo(p.x-10,p.y+24);X.moveTo(p.x,p.y+17);X.lineTo(p.x+10,p.y+24);X.stroke();if(p.say){let w=Math.min(330,35+p.line.length*13);X.fillStyle='rgba(7,10,18,.86)';rr(p.x-w/2,p.y-72,w,40,15);X.fillStyle='#fff';text(p.line,p.x,p.y-45,19,'center')}}}
function trail(u){if(u.trail.length<2||u.distract)return;X.lineCap='round';for(let i=1;i<u.trail.length;i++){let a=u.trail[i-1],b=u.trail[i],q=i/u.trail.length;X.strokeStyle=`hsla(${u.h+i*9} 96% 65%/${q*.55})`;X.lineWidth=(u.frenzy?34:u.boost?24:14)*q;X.beginPath();X.moveTo(...a);X.lineTo(...b);X.stroke()}}
function uni(u,on){let b=Math.sin(clock*12+u.h)*4,flip=Math.cos(u.a)<0?-1:1;X.save();X.translate(u.x,u.y+b);X.rotate(u.a*.1);X.scale(flip,1);if(on){X.strokeStyle='#fff';X.lineWidth=6;X.globalAlpha=.8;X.beginPath();X.arc(0,0,48+Math.sin(clock*7)*5,0,T);X.stroke();X.globalAlpha=1}if(u.frenzy){X.fillStyle=`hsla(${u.h} 95% 62%/.22)`;X.beginPath();X.arc(0,0,62+Math.sin(clock*10)*8,0,T);X.fill()}X.strokeStyle=`hsl(${u.h} 95% 60%)`;X.lineWidth=10;X.beginPath();X.moveTo(-26,2);X.quadraticCurveTo(-46,-20,-55,10);X.stroke();X.strokeStyle='#f2f2ff';X.lineWidth=8;for(let k of [-14,12]){let kick=Math.sin(clock*18+u.h+k)*12;X.beginPath();X.moveTo(k,14);X.lineTo(k+kick,37);X.stroke()}X.fillStyle=u.stun?'#c2c5d4':'#fff';X.beginPath();X.ellipse(0,0,33,20,0,0,T);X.fill();X.beginPath();X.arc(28,-13,16,0,T);X.fill();X.fillStyle=`hsl(${u.h+40} 95% 64%)`;X.beginPath();X.moveTo(34,-25);X.lineTo(53,-55);X.lineTo(43,-20);X.fill();X.fillStyle='#1e2431';X.beginPath();X.arc(34,-14,4,0,T);X.fill();X.restore();if(on||level===0){X.fillStyle='#fff';text(u.name+(u.frenzy?' • RABID':u.distract?' • DISTRACTED':''),u.x,u.y-58,20/z,'center')}}
function drawParts(){for(let p of parts){X.globalAlpha=cl(p.l*2,0,1);X.fillStyle=`hsl(${p.h} 95% 65%)`;X.fillRect(p.x,p.y,8+p.l*7,8+p.l*7)}X.globalAlpha=1}