let whip=0;
const _teachCycle=cycle;cycle=function(s){if(!level&&!s){let u=unis[caps[0]],v=Math.hypot(u.vx,u.vy);if(v>45){u.order=1.6;u.ox=Math.cos(u.a);u.oy=Math.sin(u.a);msg='ROUTE SET!';msgT=.9}return}let old=caps[s];_teachCycle(s);if(level&&wave===2&&caps[s]!==old){msg=(s?'YELLOW → ':'BLUE → ')+unis[caps[s]].name+' • '+unis[old].name+' RUNS';msgT=1.2}};
function updateIntro(){if(level)return;let s=intro.step;if(s===0&&intro.l&&unis[0].order)intro.step=1;if(s===1&&intro.r)intro.step=2;if(s===2&&intro.dash)intro.step=3}
C.addEventListener('mousedown',e=>{if(state!=='play'||e.button)return;e.preventDefault();e.stopImmediatePropagation();audio();let u=unis[caps[1]],x=(mx-ox)/z,y=(my-oy)/z,d=Math.hypot(x-u.x,y-u.y);if(d>42&&d<175){whip={x,y,i:caps[1],l:.14,hit:0};crackWhip()}else{msg=d<42?'CLICK RING, NOT UNICORN':'CLICK YELLOW RING';msgT=.7;fx(x,y,3,55);tone(110,.04,'square',.009,75)}},true);
C.addEventListener('mousedown',e=>{if(state==='title'&&!S.g('ccIntro16')){e.preventDefault();e.stopImmediatePropagation()}},true);addEventListener('keydown',e=>{if(state==='title'&&!S.g('ccIntro16')&&(e.code==='Enter'||e.code==='Space')){e.preventDefault();e.stopImmediatePropagation();audio();startLevel(0)}},true);
addEventListener('keyup',e=>{if(state==='play'&&e.code[0]==='K'&&'WASD'.includes(e.code[3])&&K[e.code]){K[e.code]=0;if(!K.KeyW&&!K.KeyA&&!K.KeyS&&!K.KeyD){let u=unis[caps[0]];if(Math.hypot(u.vx,u.vy)<60)u.vx=Math.cos(u.a)*90,u.vy=Math.sin(u.a)*90;cycle(0);e.stopImmediatePropagation()}}},true);
function crackWhip(){let w=whip,u=unis[w.i];if(!u||!u.live||caps[1]!==w.i)return w.hit=-1;let dx=u.x-w.x,dy=u.y-w.y,d=Math.hypot(dx,dy);if(d<35||d>205){w.hit=-1;msg='MISSED • LEAD TARGET';msgT=.7;tone(85,.05,'square',.01,55);return}let n=u.tapT>0?u.tap+1:1,a=Math.atan2(dy,dx),v=600+n*105;u.tap=n;u.tapT=.62;u.a=a;u.dash=.28;u.vx=Math.cos(a)*v;u.vy=Math.sin(a)*v;u.anger=cl(u.anger+.08*n,0,1);shake=Math.max(shake,3+n*2);flash=Math.max(flash,.08*n);intro.r=1;if(n>2)intro.dash=1;paintStamp(u,u.x,u.y,38+n*15);fx(w.x,w.y,5,80);fx(u.x,u.y,9+n*3,125+n*25);tone(270+n*150,.08,'triangle',.025,650+n*180);if(n===1){msg='1/3 • CHASE!';msgT=.7}if(n===2){u.boost=Math.max(u.boost,2.1);award('2/3 • CHASE!',400)}if(n>2){u.boost=Math.max(u.boost,3.8);paintStamp(u,u.x,u.y,125);for(let o of objs)if(o.hp>0&&Math.hypot(o.x+o.w/2-u.x,o.y+o.h/2-u.y)<190)hitObj(u,o,58*u.p.p);award('3X PRISM',900);u.tap=u.tapT=0;cycle(1)}w.hit=1}
function rim(u){let r=160,x=u.x<r?r:u.x>WW-r?WW-r:0,y=u.y<r?r:u.y>WH-r?WH-r:0,h=0;if(x&&y){let a=u.x-x,b=u.y-y,d=Math.hypot(a,b)||1;if(d>138){let q=138/d;u.x=x+a*q;u.y=y+b*q;u.vx*=-.6;u.vy*=-.6;h=1}}if(u.x===20||u.x===WW-20)u.vx*=-.7,h=1;if(u.y===20||u.y===WH-20)u.vy*=-.7,h=1;if(h)u.ai=u.order=0}
const _rimWorld=updateWorld;updateWorld=function(dt){_rimWorld(dt);for(let u of unis)if(u.live)rim(u)};
const _whipUpdate=update;update=function(dt){_whipUpdate(dt);if(!level&&unis[0]&&unis[0].order&&!K.KeyW&&!K.KeyA&&!K.KeyS&&!K.KeyD){let u=unis[0];u.vx=u.ox*300;u.vy=u.oy*300}if(!level&&state==='between')S.s('ccIntro16',1);if(whip&&(whip.l-=dt)<=0)whip=0};
introHud=function(){let m=['BLUE: WASD BOLT|RELEASE = LEAVE HIM RUNNING','YELLOW: CLICK MALLOW RING|CLICK = INSTANT WHIP','CHASE MALLOW • HIT 3X|3X PRISM = BIG SMASH','SMASH THE BAKERY|SPACE / BOOST / 3X HITS HARD'],a=m[intro.step].split('|');X.fillStyle='rgba(5,8,15,.94)';rr(W/2-350,H-104,700,84,18);X.fillStyle='#ffe77d';text(`${intro.step+1}/4`,W/2-320,H-70,12);X.fillStyle='#fff';text(a[0],W/2,H-72,15,'center');X.fillStyle='#bfefff';text(a[1],W/2,H-44,12,'center')};
const _whipWorld=world;world=function(){_whipWorld();if(state!=='play')return;X.save();X.translate(ox,oy);X.scale(z,z);let u=unis[caps[1]],show=level||intro.step>0;if(u&&u.live&&show){X.globalAlpha=.55+.15*Math.sin(clock*8);X.strokeStyle='#ffe56d';X.lineWidth=7;X.setLineDash([18,12]);X.beginPath();X.arc(u.x,u.y,105,0,T);X.stroke();X.setLineDash([]);X.globalAlpha=1;if(!level&&intro.step<3){X.fillStyle='#ffe56d';text(intro.step===1?'CLICK YELLOW RING':'CHASE ×3',u.x,u.y+112,16,'center')}if(u.tapT){X.strokeStyle='#fff';X.lineWidth=7;X.beginPath();X.arc(u.x,u.y,114,-T/4,-T/4+T*u.tapT/.62);X.stroke();X.fillStyle='#fff';text('×'+u.tap,u.x,u.y-128,16,'center')}}if(!level&&intro.step===0){u=unis[caps[0]];X.fillStyle='#a8f3ff';text('WASD',u.x,u.y-105,18,'center')}if(whip){u=unis[whip.i];if(u){let ex=u.x,ey=u.y,dx=ex-whip.x,dy=ey-whip.y,d=Math.hypot(dx,dy)||1,cx=(whip.x+ex)/2-dy/d*55,cy=(whip.y+ey)/2+dx/d*55;X.lineCap='round';for(let q of [[13,'#ff5f83'],[8,'#ffe56d'],[4,'#64dcff']]){X.strokeStyle=q[1];X.lineWidth=q[0];X.beginPath();X.moveTo(whip.x,whip.y);X.quadraticCurveTo(cx,cy,ex,ey);X.stroke()}X.fillStyle=whip.hit<0?'#fff':'#ffe56d';X.beginPath();X.arc(whip.x,whip.y,13+Math.sin(clock*18)*3,0,T);X.fill()}}X.restore()};
const _whipDraw=draw;draw=function(){_whipDraw();X.save();X.translate(mx,my);for(let i=3;i--;){X.strokeStyle=`hsl(${clock*90+i*120} 100% 65%)`;X.lineWidth=4+i*3;X.beginPath();X.arc(-7,7,14+i*7,.2,5.6);X.stroke()}X.strokeStyle='#fff';X.lineWidth=3;X.beginPath();X.arc(0,0,5,0,T);X.moveTo(-8,0);X.lineTo(8,0);X.moveTo(0,-8);X.lineTo(0,8);X.stroke();X.restore()};
