let whip=0,suggested=-1;
/* YELLOW: CLICK MALLOW RING */
function roadAt(u){if(!u||!PM)return 0;let x=cl(u.x/PS|0,0,PW-1),y=cl(u.y/PS|0,0,PH-1);return PM[y*PW+x]}
function bestIdle(){let j=-1,b=-1;for(let i=unis.length;i--;){let u=unis[i];if(u.live&&i!==caps[0]&&u.cool>b)b=u.cool,j=i}return j}
const _soloStart=startLevel;startLevel=function(n){_soloStart(n);caps=[0,-1];suggested=-1;for(let i=unis.length;i--;){let u=unis[i];u.power=0;u.cool=i/5;u.tap=u.tapT=0}};
capSide=i=>i===caps[0]?1:0;
const _soloAI=moveAI;moveAI=function(u,d){let c=caps[1];caps[1]=caps[0];let a=_soloAI(u,d);caps[1]=c;return a};
const _soloDistract=distractForce;distractForce=function(u){let f=_soloDistract(u);if(u!==unis[caps[0]]&&roadAt(u))f[0]*=.55,f[1]*=.55;return f};
cycle=function(){if(state!=='play')return;if(!level&&intro.step!==3){msg='FOLLOW LESSON';msgT=.6;return}let o=caps[0],u=unis[o];if(Math.hypot(u.vx,u.vy)>35)u.order=roadAt(u)?5.2:4,u.ox=Math.cos(u.a),u.oy=Math.sin(u.a);if(level)dmask|=dmask&16?32:16;let j=o;do j=(j+1)%unis.length;while(!unis[j].live&&j!==o);caps[0]=j;u=unis[j];u.order=u.cool=0;u.distract=Math.max(0,u.distract-.2);cue[0]=1.1;cueWhy[0]=0;if(!level)intro.step=4;msg='CONTROL → '+u.name;msgT=1};
const _soloWave=waveUp;waveUp=function(w){_soloWave(w);if(level)msg=w===2?'4 UNICORNS • SHIFT':'ALL 6 • YOU CONDUCT',msgT=2};
function dashSolo(){if(state!=='play'||dashCd)return;let u=unis[caps[0]],n=u.power|0;if(!n){msg='WHIP → CHARGE';msgT=.7;return}if(!level&&!((intro.step===2&&caps[0]===0)||(intro.step===5&&caps[0]===1))){msg='CHARGE 5/5';msgT=.7;return}dashCd=.35;u.dash=.2+n*.09;let v=560+n*110;u.vx=Math.cos(u.a)*v;u.vy=Math.sin(u.a)*v;paintStamp(u,u.x,u.y,38+n*12);fx(u.x,u.y,6+n*2,120);tone(150+n*35,.1,'sawtooth',.03);u.power=u.tap=u.tapT=0;if(n===5)award('MAX DASH',850);if(!level){if(intro.step===2){intro.step=3;msg='SHIFT → MALLOW';msgT=1}else{S.s('ccIntro10',1);S.s('ccIntro16',1);state='between'}}}
C.addEventListener('mousedown',e=>{if(state!=='play'||e.button)return;e.preventDefault();e.stopImmediatePropagation();audio();if(!level&&intro.step!==1&&intro.step!==4){msg=intro.step?'FOLLOW LESSON':'MOVE FIRST';msgT=.5;return}let u=unis[caps[0]],x=(mx-ox)/z,y=(my-oy)/z,d=Math.hypot(x-u.x,y-u.y);if(d>38&&d<180)whip={x,y,i:caps[0],l:.12,hit:0},crackWhip();else msg='WHIP RING',msgT=.5},true);
C.addEventListener('mousedown',e=>{if(state==='title'&&!S.g('ccIntro16'))e.preventDefault(),e.stopImmediatePropagation(),audio(),startLevel(0)},true);
addEventListener('keydown',e=>{if(state==='title'&&!S.g('ccIntro16')&&(e.code==='Enter'||e.code==='Space')){e.preventDefault();e.stopImmediatePropagation();audio();startLevel(0);return}if(state!=='play'||e.repeat)return;if(e.code.startsWith('Shift'))e.preventDefault(),e.stopImmediatePropagation(),cycle();else if(e.code==='Space')e.preventDefault(),e.stopImmediatePropagation(),dashSolo()},true);
addEventListener('keyup',e=>{if(state==='play'&&'WASD'.includes(e.code[3]))K[e.code]=0,e.stopImmediatePropagation()},true);
function crackWhip(){let w=whip,u=unis[w.i];if(!u||caps[0]!==w.i)return;let x=u.x-w.x,y=u.y-w.y,d=Math.hypot(x,y);if(d<32||d>210){w.hit=-1;return msg='MISS',msgT=.4}let c=u.tapT?u.tap+1:1,n=Math.min(5,(u.power|0)+1),a=Math.atan2(y,x);u.power=n;u.tap=c;u.tapT=.7;u.a=a;u.vx+=Math.cos(a)*(80+n*25);u.vy+=Math.sin(a)*(80+n*25);paintStamp(u,u.x,u.y,26+n*8);fx(u.x,u.y,4+n,85);tone(900+n*85,.035,'square',.03,180+n*35);tone(210+n*45,.055,'triangle',.018);msg=u.name+' • '+n+'/5';msgT=.45;if(c===2)award('2X WHIP',260);if(c>2){award('3X PRISM',700);paintStamp(u,u.x,u.y,92);for(let o of objs)if(o.hp>0&&Math.hypot(o.x+o.w/2-u.x,o.y+o.h/2-u.y)<150)hitObj(u,o,34*u.p.p);u.tap=0}if(!level&&n===5){if(intro.step===1&&caps[0]===0)intro.step=2;if(intro.step===4&&caps[0]===1)intro.step=5}w.hit=1}
const _soloWorld=updateWorld;updateWorld=function(d){let a=unis[caps[0]],fast=[];for(let u of unis)if(u.live&&u!==a&&roadAt(u))u.p.sp*=1.1,fast.push(u);_soloWorld(d);for(let u of fast)u.p.sp/=1.1;for(let u of unis)if(u.live)u===a?u.cool=0:u.cool=(u.cool||0)+d*(u.order||u.frenzy||u.boost?.2:Math.hypot(u.vx,u.vy)<75?1.8:1);suggested=bestIdle()};
function updateIntro(){if(!level&&!intro.step&&intro.l)intro.step=1}
const _soloUpdate=update;update=function(d){_soloUpdate(d);if(whip&&(whip.l-=d)<=0)whip=0};
introHud=function(){let m=['1/6 • WASD MOVE BOLT','2/6 • WHIP BOLT ×5','3/6 • SPACE DASH BOLT','4/6 • SHIFT TO MALLOW','5/6 • WHIP MALLOW ×5','6/6 • SPACE DASH MALLOW'];X.fillStyle='#fff';text(m[intro.step],W/2,H-28,15,'center')};
hud=function(){X.setTransform(1,0,0,1,0,0);if(!level)return introHud();let n=LM.slice(0,-1).filter(lmDone).length,u=unis[caps[0]],s=unis[suggested];X.fillStyle='rgba(5,8,15,.88)';rr(18,16,W-36,48,14);X.fillStyle='#fff';text(n<4?'BREAK '+n+'/4':takeover()<.28?'PAINT • CHAOS '+(takeover()*100|0)+'/28':'HALL READY',34,46,13);text('YOU '+u.name+' • DASH '+(u.power|0)+'/5'+(s?' • NEXT '+s.name:''),W/2,46,13,'center');text(timeLeft.toFixed(1)+'s • '+comp(),W-34,46,13,'right');text('PAINT TOWN • WHIP ×5 • SPACE DASH • SHIFT SWITCH • PAINT=HIGHWAY',W/2,H-14,11,'center')};
title=function(){X.fillStyle='#10142d';X.fillRect(0,0,W,H);X.fillStyle='#fff';text('UNICORN STAMPEDE',W/2,165,52,'center');text('CONTROL ONE UNICORN • ORCHESTRATE THE REST',W/2,255,16,'center');text('WASD MOVE • WHIP ×5 = LONGER DASH • SPACE DASH • SHIFT SWITCH',W/2,310,14,'center');text('PAINT THE TOWN • KEEP HERD MOVING • BREAK 4 + 28% CHAOS • SMASH HALL',W/2,360,14,'center');text('RAINBOW PAINT = FASTER, STUBBORNER AUTONOMOUS ROUTES',W/2,405,13,'center');text(S.g('ccIntro16')?'ENTER TOWN':'ENTER 2-UNICORN TRAINING',W/2,500,18,'center')};
between=function(){X.fillStyle='#10142d';X.fillRect(0,0,W,H);X.fillStyle='#fff';text('TRAINING COMPLETE',W/2,185,36,'center');text('PAINT THE TOWN • KEEP UNICORNS RUNNING',W/2,265,18,'center');text('WHIP ×5 → LONG DASH • SHIFT → HAND OFF CONTROL',W/2,315,15,'center');text('PAINTED STREETS ARE RAINBOW HIGHWAYS FOR AUTONOMOUS UNICORNS',W/2,365,14,'center');text('BREAK 4 LANDMARKS + 28% CHAOS • THEN SMASH TOWN HALL',W/2,415,15,'center');text('ENTER TOWN',W/2,500,20,'center')};
const _soloWorldDraw=world;world=function(){_soloWorldDraw();if(state!=='play')return;X.save();X.translate(ox,oy);X.scale(z,z);let u=unis[caps[0]],s=unis[suggested],n=u.power|0;X.strokeStyle='#fff';X.lineWidth=7+n;X.beginPath();X.arc(u.x,u.y,78+n*3,0,T);X.stroke();X.fillStyle='#fff';text('DASH '+n+'/5',u.x,u.y-94-n*3,14,'center');if(u.tapT)text(['','HEY!','RUDE!','WHEE!','AGAIN?!','MAX!'][n],u.x,u.y-120-n*3,15,'center');if(level&&s&&s.cool>1.5){X.fillStyle='#ffb7e8';text('NEXT',s.x,s.y-55,12,'center')}if(whip){let q=unis[whip.i];if(q){X.strokeStyle=`hsl(${clock*180} 95% 65%)`;X.lineWidth=7;X.beginPath();X.moveTo(whip.x,whip.y);X.lineTo(q.x,q.y);X.stroke()}}X.restore()};
const _soloDraw=draw;draw=function(){_soloDraw();X.fillStyle='#fff';X.fillRect(mx-7,my-1,14,2);X.fillRect(mx-1,my-7,2,14)};
