let whip=0,suggested=-1;
/* release-prune compatibility: YELLOW: CLICK MALLOW RING */
function roadAt(u){if(!u||!PM)return 0;let x=cl(u.x/PS|0,0,PW-1),y=cl(u.y/PS|0,0,PH-1);return PM[y*PW+x]}
function bestIdle(){let j=-1,b=-1;for(let u of unis)if(u.live&&u.id!==caps[0]&&u.cool>b)b=u.cool,j=u.id;return j}
const _soloStart=startLevel;startLevel=function(n){_soloStart(n);caps[0]=0;caps[1]=-1;suggested=-1;for(let i=0;i<unis.length;i++){let u=unis[i];u.power=0;u.cool=i*.22;u.tap=u.tapT=0}};
capSide=function(i){return i===caps[0]?1:0};
const _soloAI=moveAI;moveAI=function(u,dt){let c=caps[1];caps[1]=caps[0];let a=_soloAI(u,dt);caps[1]=c;return a};
const _soloDistract=distractForce;distractForce=function(u){let f=_soloDistract(u);if(u.id!==caps[0]&&roadAt(u))f[0]*=.55,f[1]*=.55;return f};
cycle=function(){if(state!=='play')return;let old=caps[0],u=unis[old],v=Math.hypot(u.vx,u.vy);if(v>35){u.order=roadAt(u)?5.2:4;u.ox=Math.cos(u.a);u.oy=Math.sin(u.a)}if(level)dmask|=dmask&16?32:16;let j=bestIdle();if(j<0){let a=unis.filter(q=>q.live).map(q=>q.id),k=a.indexOf(old);j=a[(k+1)%a.length]}caps[0]=j;caps[1]=-1;u=unis[j];u.order=0;u.cool=0;u.distract=Math.max(0,u.distract-.2);cue[0]=1.15;cueWhy[0]=0;if(!level)intro.power=1;msg='CONTROL → '+u.name;msgT=1;tone(420,.06,'triangle',.018,650)};
const _soloWave=waveUp;waveUp=function(w){_soloWave(w);if(level){msg=w===2?'4 UNICORNS • SHIFT TO SWITCH':'ALL 6 • YOU CONDUCT THE CHAOS';lmText=w===2?'MANUAL SWITCHING':'FULL HERD';lmTextT=2}};
function dashSolo(){if(state!=='play'||dashCd)return;let u=unis[caps[0]],n=u.power|0;if(!n){msg='WHIP TO CHARGE DASH';msgT=.7;tone(95,.05,'square',.01,60);return}dashCd=.35;dashT=.28+n*.07;dashHit=0;u.dash=dashT;u.anger=cl(u.anger+.08*n,0,1);let v=580+n*145;u.vx=Math.cos(u.a)*v;u.vy=Math.sin(u.a)*v;paintStamp(u,u.x,u.y,38+n*12);fx(u.x,u.y,9+n*4,120+n*30);tone(120+n*45,.13,'sawtooth',.035,480+n*110);u.power=u.tap=u.tapT=0;intro.dash=1;if(n===3)award('PRISM DASH',850);else{msg='DASH!';msgT=.6}}
C.addEventListener('mousedown',e=>{if(state!=='play'||e.button)return;e.preventDefault();e.stopImmediatePropagation();audio();let u=unis[caps[0]],x=(mx-ox)/z,y=(my-oy)/z,d=Math.hypot(x-u.x,y-u.y);if(d>38&&d<180){whip={x,y,i:caps[0],l:.14,hit:0};crackWhip()}else{msg=d<38?'AIM BESIDE UNICORN':'CLICK THE WHIP RING';msgT=.65;fx(x,y,3,50);tone(105,.04,'square',.008,70)}},true);
C.addEventListener('mousedown',e=>{if(state==='title'&&!S.g('ccIntro16')){e.preventDefault();e.stopImmediatePropagation();audio();startLevel(0)}},true);
addEventListener('keydown',e=>{if(state==='title'&&!S.g('ccIntro16')&&(e.code==='Enter'||e.code==='Space')){e.preventDefault();e.stopImmediatePropagation();audio();startLevel(0);return}if(state!=='play'||e.repeat)return;if(e.code==='ShiftLeft'||e.code==='ShiftRight'){e.preventDefault();e.stopImmediatePropagation();audio();cycle()}else if(e.code==='Space'){e.preventDefault();e.stopImmediatePropagation();audio();dashSolo()}},true);
addEventListener('keyup',e=>{if(state==='play'&&['KeyW','KeyA','KeyS','KeyD'].includes(e.code)){K[e.code]=0;e.stopImmediatePropagation()}},true);
function crackWhip(){let w=whip,u=unis[w.i];if(!u||!u.live||caps[0]!==w.i)return w.hit=-1;let dx=u.x-w.x,dy=u.y-w.y,d=Math.hypot(dx,dy);if(d<32||d>210){w.hit=-1;msg='MISSED • LEAD THE RING';msgT=.65;tone(82,.05,'square',.009,55);return}let chain=u.tapT>0?u.tap+1:1,p=u.power|0,n=Math.min(3,p+1),a=Math.atan2(dy,dx),v=90+n*35;u.power=n;u.tap=chain;u.tapT=.62;u.a=a;u.vx+=Math.cos(a)*v;u.vy+=Math.sin(a)*v;u.anger=cl(u.anger+.035*n,0,1);shake=Math.max(shake,2+chain);flash=Math.max(flash,.05*chain);intro.r=1;if(n===3)intro.rescue=1;paintStamp(u,u.x,u.y,28+n*9);fx(w.x,w.y,4,70);fx(u.x,u.y,6+chain*2,90+chain*20);tone(260+chain*120,.065,'triangle',.02,600+chain*140);if(chain===1){msg='DASH '+n+'/3';msgT=.55}if(chain===2)award('2X WHIP',260);if(chain>2){award('3X PRISM',700);paintStamp(u,u.x,u.y,92);for(let o of objs)if(o.hp>0&&Math.hypot(o.x+o.w/2-u.x,o.y+o.h/2-u.y)<150)hitObj(u,o,34*u.p.p);u.tap=u.tapT=0}if(p<3&&n===3){msg='PRISM DASH READY';msgT=.9}w.hit=1}
function rim(u){let r=160,x=u.x<r?r:u.x>WW-r?WW-r:0,y=u.y<r?r:u.y>WH-r?WH-r:0,h=0;if(x&&y){let a=u.x-x,b=u.y-y,d=Math.hypot(a,b)||1;if(d>138){let q=138/d;u.x=x+a*q;u.y=y+b*q;u.vx*=-.6;u.vy*=-.6;h=1}}if(u.x===20||u.x===WW-20)u.vx*=-.7,h=1;if(u.y===20||u.y===WH-20)u.vy*=-.7,h=1;if(h)u.ai=u.order=0}
const _soloWorld=updateWorld;updateWorld=function(dt){let fast=[];for(let u of unis)if(u.live&&u.id!==caps[0]&&roadAt(u)){u.p.sp*=1.1;fast.push(u)}_soloWorld(dt);for(let u of fast)u.p.sp/=1.1;for(let u of unis)if(u.live){if(u.id===caps[0])u.cool=0;else u.cool=(u.cool||0)+dt*(u.order||u.frenzy||u.boost?.2:Math.hypot(u.vx,u.vy)<75?1.8:1);rim(u)}suggested=bestIdle()};
function updateIntro(){if(level)return;let s=intro.step;if(s===0&&intro.l)intro.step=1;if(s===1&&intro.r)intro.step=2;if(s===2&&intro.rescue&&intro.dash&&intro.power)intro.step=3}
const _soloUpdate=update;update=function(dt){_soloUpdate(dt);if(!level&&state==='between')S.s('ccIntro16',1);if(whip&&(whip.l-=dt)<=0)whip=0};
introHud=function(){let a=intro.step===0?['WASD • MOVE BOLT','ONE UNICORN • FULL CONTROL']:intro.step===1?['MOUSE • WHIP THE RING','EVERY HIT CHARGES DASH']:intro.step===2&&!intro.rescue?['WHIP ×3','FILL THE PRISM DASH']:intro.step===2&&!intro.dash?['SPACE • DASH','SPEND YOUR CHARGE']:intro.step===2&&!intro.power?['SHIFT • SWITCH','AI POINTS TO THE MOST NEGLECTED']:['SMASH THE BAKERY','PAINT BECOMES RAINBOW HIGHWAY'];X.fillStyle='rgba(5,8,15,.94)';rr(W/2-350,H-104,700,84,18);X.fillStyle='#ffe77d';text(`${Math.min(intro.step+1,4)}/4`,W/2-320,H-70,12);X.fillStyle='#fff';text(a[0],W/2,H-72,15,'center');X.fillStyle='#bfefff';text(a[1],W/2,H-44,12,'center')};
hud=function(){X.setTransform(1,0,0,1,0,0);if(!level){introHud();if(lmTextT){X.fillStyle='rgba(5,8,15,.9)';rr(W/2-210,175,420,48,15);X.fillStyle='#ffe56d';text(lmText,W/2,207,19,'center')}return}let n=LM.slice(0,-1).filter(lmDone).length,ready=n>3&&takeover()>=.28,u=unis[caps[0]],s=unis[suggested],cover=u&&u.y*z+oy<110;if(!cover){X.fillStyle='rgba(5,8,15,.92)';rr(18,16,350,94,16);X.fillStyle=ready?'#ffe56d':'#fff';text(n<4?`${n}/4 → UNLOCK HALL`:ready?'TOWN HALL UNLOCKED':`CHAOS ${(takeover()*100)|0}/28% → HALL`,34,45,17);X.fillStyle=stamp>3?'#ffe56d':'#aeb7cc';text(`PAINT ${(paintPct()*100).toFixed(1)}% • ACTIVE ${stamp}/6`,34,67,12);for(let i=0;i<5;i++){let l=LM[i],x=42+i*52;X.fillStyle=lmDone(l)?'#77efa2':l.k==='hall'&&!ready?'#56617a':'#ff79ae';X.beginPath();X.arc(x,91,11,0,T);X.fill();X.fillStyle='#fff';text(['B','M','G','C','H'][i],x,95,9,'center')}X.fillStyle='rgba(5,8,15,.92)';rr(W-214,16,196,92,16);X.fillStyle=timeLeft<15?'#ff707b':'#fff';text(`${timeLeft.toFixed(1)}s`,W-36,42,19,'right');X.fillStyle='#ffe56d';text(`${tier()} • ${comp()}`,W-36,64,11,'right');X.fillStyle=u.power===3?'#ffe56d':'#a8f3ff';text(u.power===3?'PRISM DASH READY':`DASH ${u.power|0}/3`,W-36,86,11,'right')}X.fillStyle='rgba(5,8,15,.86)';rr(W/2-235,18,470,46,13);X.fillStyle='#fff';text(`YOU • ${u.name}`,W/2-210,47,13);if(s){X.fillStyle='#ff9de0';text(`AI NEXT • ${s.name}`,W/2+210,47,12,'right')}if(msgT){X.fillStyle='rgba(5,8,15,.9)';rr(W/2-220,70,440,32,10);X.fillStyle='#ffe56d';text(msg,W/2,92,13,'center')}let h=wave<2?'WASD MOVE • MOUSE WHIP = CHARGE • SPACE DASH':'SHIFT = SWITCH • PAINT = +10% AUTO SPEED + LONGER ROUTES';X.fillStyle='rgba(5,8,15,.82)';rr(W/2-330,H-34,660,26,9);X.fillStyle='#dff7ff';text(h,W/2,H-16,11,'center')};
title=function(){let g=X.createLinearGradient(0,0,W,H);g.addColorStop(0,'#07152d');g.addColorStop(1,'#511947');X.fillStyle=g;X.fillRect(0,0,W,H);for(let i=0;i<6;i++){let x=290+i*140,y=220+(i%2)*20;X.strokeStyle=`hsl(${hues[i]} 95% 62%)`;X.lineWidth=15;X.beginPath();X.moveTo(x-72,y+8);X.lineTo(x-15,y);X.stroke();X.fillStyle='#fff';X.beginPath();X.ellipse(x,y,27,16,0,0,T);X.fill();X.beginPath();X.arc(x+26,y-12,13,0,T);X.fill();X.fillStyle=`hsl(${hues[i]} 95% 62%)`;X.beginPath();X.moveTo(x+33,y-22);X.lineTo(x+49,y-50);X.lineTo(x+42,y-17);X.fill()}X.fillStyle='#fff';text('UNICORN STAMPEDE',W/2,105,58,'center');X.fillStyle='#ffe77d';text('6 UNICORNS • CONTROL 1 • THE HERD KEEPS RUNNING',W/2,300,17,'center');X.fillStyle='#a8f3ff';text('WASD MOVE • MOUSE WHIP = CHARGE',W/2,342,14,'center');X.fillStyle='#ffe77d';text('SPACE DASH • SHIFT SWITCH',W/2,376,14,'center');X.fillStyle='#77efa2';text('PAINT BUILDS RAINBOW HIGHWAYS FOR AUTONOMY',W/2,410,13,'center');X.fillStyle='#fff';text('BREAK 4 + 28% CHAOS → TOWN HALL',W/2,442,13,'center');X.fillStyle='#fff';rr(W/2-200,510,400,62,18);X.fillStyle='#171a2b';text(S.g('ccIntro16')?'START STAMPEDE':'ENTER: START CONTROL LESSON',W/2,549,16,'center')};
between=function(){X.fillStyle='#0b1120';X.fillRect(0,0,W,H);X.fillStyle='#ffe56d';text('CONTROL LESSON COMPLETE!',W/2,190,36,'center');X.fillStyle='#a8f3ff';text('ONE CAPTAIN • SIX PROBLEMS • YOUR SWITCH, YOUR CHAOS',W/2,285,17,'center');X.fillStyle='#fff';text('WHIP → CHARGE → DASH • SHIFT WHEN YOU WANT',W/2,330,15,'center');X.fillStyle='#77efa2';text('RAINBOW PAINT HELPS THE AUTONOMOUS HERD RUN',W/2,365,14,'center');X.fillStyle='#fff';rr(W/2-170,450,340,62,18);X.fillStyle='#171a2b';text('START STAMPEDE',W/2,489,17,'center')};
const _soloWorldDraw=world;world=function(){_soloWorldDraw();if(state!=='play')return;X.save();X.translate(ox,oy);X.scale(z,z);let u=unis[caps[0]];if(u&&u.live){X.globalAlpha=.7+.18*Math.sin(clock*8);X.strokeStyle='#fff';X.lineWidth=7;X.setLineDash([20,10]);X.beginPath();X.arc(u.x,u.y,106,0,T);X.stroke();X.setLineDash([]);X.globalAlpha=1;for(let i=0;i<3;i++){X.strokeStyle=i<(u.power|0)?['#ff6c91','#ffe56d','#72e8ff'][i]:'#455064';X.lineWidth=8;X.beginPath();X.arc(u.x,u.y,118,-Math.PI/2+i*T/3,-Math.PI/2+(i+.72)*T/3);X.stroke()}}let s=unis[suggested];if(level&&s&&s.live&&s.cool>1.5){X.strokeStyle='#ff9de0';X.lineWidth=5;X.setLineDash([12,10]);X.beginPath();X.arc(s.x,s.y,76+Math.sin(clock*7)*5,0,T);X.stroke();X.setLineDash([]);X.fillStyle='#ffb7e8';text('SHIFT → '+s.name,s.x,s.y+98,14,'center')}if(whip){u=unis[whip.i];if(u){let dx=u.x-whip.x,dy=u.y-whip.y,d=Math.hypot(dx,dy)||1,cx=(whip.x+u.x)/2-dy/d*50,cy=(whip.y+u.y)/2+dx/d*50;X.lineCap='round';for(let q of [[12,'#ff5f83'],[7,'#ffe56d'],[4,'#64dcff']]){X.strokeStyle=q[1];X.lineWidth=q[0];X.beginPath();X.moveTo(whip.x,whip.y);X.quadraticCurveTo(cx,cy,u.x,u.y);X.stroke()}}}X.restore()};
const _soloDraw=draw;draw=function(){_soloDraw();X.save();X.translate(mx,my);for(let i=3;i--;){X.strokeStyle=`hsl(${clock*90+i*120} 100% 65%)`;X.lineWidth=4+i*3;X.beginPath();X.arc(-7,7,14+i*7,.2,5.6);X.stroke()}X.strokeStyle='#fff';X.lineWidth=3;X.beginPath();X.arc(0,0,5,0,T);X.moveTo(-8,0);X.lineTo(8,0);X.moveTo(0,-8);X.lineTo(0,8);X.stroke();X.restore()};
