let zone=S.g('ccZone')%3,runN=S.g('ccRun'),seedZone=0,pwash=[],washT=0,heli=0,wind=1,windT=0,splash=0,chains=0,crowns=0;
const ZN=['PRISMBOROUGH','WASHWATER BAY','CLOUDTOP HEIGHTS'],_day=today;today=()=>_day()+seedZone*173+runN*19;
function grade(){return landWin?1+(paintPct()>[.6,.48,.54][zone])+(chains>=[2,2,3][zone]):0}
function finishZone(){crowns=grade();let k='ccC'+zone;if(crowns>S.g(k))S.s(k,crowns)}
const _startW=startLevel;startLevel=function(n){let prev=state,won=landWin;if(n&&prev==='end'&&won){zone=(zone+1)%3;S.s('ccZone',zone)}seedZone=n?zone:0;if(n)S.s('ccRun',++runN);_startW(n);pwash=[];heli=0;wind=1;windT=2;splash=washT=chains=crowns=0;if(n){timeLeft=[100,94,90][zone];if(zone===1){addClean(1);pwash=people.slice(0,3);heli={x:120,y:230,v:210,t:2.2}}lmText=ZN[zone];lmTextT=2}};
const _crackW=crackWhip;crackWhip=function(){let u=unis[whip.i],n=u&&u.tapT?u.tap+1:1;_crackW();if(whip&&whip.hit>0){u=unis[whip.i];if(n>2)chains++;if(zone===2&&level&&u){u.tapT=Math.min(u.tapT,.5);u.vx*=1.14;u.vy*=1.14}}};
function updateZone(dt){if(!level)return;splash=Math.max(0,splash-dt);if(zone===1){washT-=dt;let d=0;for(let i=1;i<4;i++)if(district(i)>district(d))d=i,0;let tx=(d%2? .75:.25)*WW,ty=(d>1?.75:.25)*WH;for(let p of pwash){p.vx+=(tx-p.x)*dt*.16;p.vy+=(ty-p.y)*dt*.16}if(washT<=0){washT=.34;for(let p of pwash)eraseStamp(p.x,p.y,24)}if(heli){heli.x+=heli.v*dt;if(heli.x>WW+120)heli.x=-120;heli.t-=dt;if(heli.t<=0){heli.t=3.2;let x=tx+R(320,-320),y=ty+R(250,-250);eraseStamp(x,y,115);splash=.55;heli.dx=x;heli.dy=y;msg='HELICOPTER WATER DROP!';msgT=.8;tone(105,.15,'sine',.02,60)}}}else if(zone===2){windT-=dt;if(windT<=0){windT=4;wind*=-1;lmText=wind>0?'CROSSWIND →':'← CROSSWIND';lmTextT=1}for(let u of unis)if(u.live)u.vx+=wind*125*dt}}
const _updateW=update;update=function(dt){let before=state;_updateW(dt);if(state==='play'&&!paused)updateZone(dt);if(before==='play'&&state==='end')finishZone()};
const _worldW=world;world=function(){_worldW();if(!level)return;X.save();X.translate(ox,oy);X.scale(z,z);if(zone===1){X.strokeStyle='#7edfff';X.lineWidth=5;for(let p of pwash){X.beginPath();X.moveTo(p.x,p.y);X.lineTo(p.x+28,p.y-18);X.stroke()}if(heli){X.save();X.translate(heli.x,heli.y);X.fillStyle='#dfe9f5';rr(-42,-15,84,30,10);X.fillStyle='#26394c';X.fillRect(-8,-22,16,44);X.fillRect(-58,-3,116,6);X.restore()}if(splash){X.strokeStyle=`rgba(105,210,255,${splash})`;X.lineWidth=18;X.beginPath();X.arc(heli.dx,heli.dy,120*(1-splash*.4),0,T);X.stroke()}}else if(zone===2){X.fillStyle='rgba(245,250,255,.09)';for(let i=0;i<7;i++){let x=(i*510+clock*wind*45)%3500-120,y=180+(i%3)*560;X.beginPath();X.ellipse(x,y,180,70,0,0,T);X.fill()}}X.restore()};
const _hudW=hud;hud=function(){_hudW();if(level){X.fillStyle='#d8e9ff';text(ZN[zone],W/2,61,10,'center')}};
const _titleW=title;title=function(){_titleW();if(S.g('ccIntro10')){X.fillStyle='#d8e9ff';text(`CAMPAIGN • ${ZN[zone]} • ${'★'.repeat(S.g('ccC'+zone))}`,W/2,470,13,'center')}};
const _endW=end;end=function(){_endW();if(!level)return;let c=grade();X.fillStyle='rgba(5,8,15,.88)';rr(W/2-245,382,490,44,13);X.fillStyle='#ffe56d';text(`${ZN[zone]} • ${'★'.repeat(c)}${'☆'.repeat(3-c)}`,W/2,410,16,'center');X.fillStyle='#d4f8ff';text(landWin?`NEXT: ${ZN[(zone+1)%3]}`:`RETRY: ${ZN[zone]}`,W/2,515,13,'center')};
